version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app  # Mount local directory to the container
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload", "--reload-dir", "/app"]


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1471
      POSTGRES_DB: mailgen-db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: