version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1471
      POSTGRES_DB: mailgen-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: